### ISSUE TITLE
Feature request: #channel mentions

### ISSUE THREAD

**Issue by cruzecontrol** [hubot-scripts/hubot-factoids#1]
Any way to get #channel mentions in the factoid message to be live links to those channels?  Slackbot responses do this but I'd rather use factoids.

**Comment by therealklanni** [comment]
I believe this is controlled with the `HUBOT_SLACK_LINK_NAMES` env var.

This sort of behavior is controlled by the Hubot adapter (in your case: hubot-slack), so it's out of the scope of this script.
