### ISSUE TITLE
does not load facts if DB loaded before factoids script loads

### ISSUE THREAD

**Issue by yorickvP** [hubot-scripts/hubot-factoids#2]
When using the file-brain, the brain is loaded synchronously, and the 'loaded' event is emitted before any other script even runs. This causes this script to not load the factoids in the database at all. 

My current workaround is to add `@data = @robot.brain.data.factoids ?= {}` in the Factoids constructor, but this might not be ideal.

**Comment by therealklanni** [comment]
Thanks, I will have a look.

**Comment by therealklanni** [comment]
Should be resolved now in v0.2.6
