### ISSUE TITLE
Why must keys be greater than 3 characters? Is this documented?

### ISSUE THREAD

**Issue by victorhooi** [hubot-scripts/hubot-factoids#3]
Is there a particular reason that keys have to be more than 3 characters?

Also, would it be possible to document this fact somewhere (e.g. README) - I got tripped up by this until I viewed the source.

**Comment by therealklanni** [comment]
It's just to prevent spammy factoids.

I'm happy to accept a PR to update the docs and/or make the character limit configurable.

**Comment by dylanh724** [comment]
I'd like an env var for char limit too :)

**Comment by therealklanni** [comment]
Sounds good. Let's just close this and I'll await the PR. Thanks.
