### ISSUE TITLE
Default port for HUBOT_BASE_URL is 8080, example uses port 5555

### ISSUE THREAD

**Issue by victorhooi** [hubot-scripts/hubot-factoids#4]
The default port for Hubot (via Express) is 8080.

However, the README uses port 5555 as an example when discussing setting `HUBOT_BASE_URL`:

```
HUBOT_BASE_URL [required] - URL of Hubot (ex. http://myhubothost.com:5555/)
```

It would make more sense to use port 8080, or at least make it clear than if you set the `HUBOT_BASE_URL` to a different port, you will also need to change the Express port.

**Comment by therealklanni** [comment]
It may have changed. I believe it was originally 5555 by default, hence the documentation being written that way.
